// Copyright 2014 Claudemiro Alves Feitosa Neto. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package main

import (
	"flag"
	"fmt"

	"ipe"
)

// These variables are generated by the linker
// please see the makefile for more information.
var (
	version        string
	buildtime      string
	githash        string
	isShowVersion  = false
	configFilename string
)

// Main function, initialize the system
func main() {
	parseFlags()

	fmt.Printf("\033[32mIpe %s@%s (built: %s)\033[0m\n", version, githash, buildtime)
	fmt.Println("\033[32mhttps://github.com/dimiro1/ipe\033[0m")

	if isShowVersion {
		return
	}

	printBanner()

	ipe.Start(configFilename)
}

// Print a beautiful banner
func printBanner() {
	fmt.Print("\033[31m")
	fmt.Print(`  
d8b                   
Y8P                   
                      
888 88888b.   .d88b.  
888 888 "88b d8P  Y8b 
888 888  888 88888888 
888 888 d88P Y8b.     
888 88888P"   "Y8888  
    888               
    888               
    888               
`)
	fmt.Println("\033[0m")
}

func parseFlags() {
	flag.BoolVar(&isShowVersion, "version", false, "Show version info")
	flag.StringVar(&configFilename, "config", "config.yml", "Configuration yaml file path")
	flag.Parse()
}
